name: CD with Gradle

on:
  push:
    branches:
      - main
  pull_request:
    types: [closed]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Set Up Locales
        run: |
          sudo apt-get update
          sudo apt-get install -y locales
          sudo locale-gen ko_KR.UTF-8
          sudo update-locale LANG=ko_KR.UTF-8
          export LANG=ko_KR.UTF-8
          export LANGUAGE=ko_KR:en
          export LC_ALL=ko_KR.UTF-8

      - name: Make application.yml
        run: |
          mkdir -p ./src/main/resources
          echo "${{ secrets.YML }}" > ./src/main/resources/application.yml
        shell: bash

      - name: Build with Gradle
        run: |
          chmod +x ./gradlew
          ./gradlew clean build -x test

      - name: Docker build & push to Docker Hub
        run: |
          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
          docker build -t ${{ secrets.DOCKER_REPO }}/beatbuddy .
          docker push ${{ secrets.DOCKER_REPO }}/beatbuddy

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ubuntu
          key: ${{ secrets.KEY }}
          script: |
            sudo docker-compose down
            sudo docker pull ${{ secrets.DOCKER_REPO }}/beatbuddy
            sudo docker-compose up --build -d
            sudo docker image prune -f
